# Generated by Django 4.2.18 on 2025-01-20 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('CASH', 'Efectivo'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWING', 'En Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='status')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='proof of payment')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validated at')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation', verbose_name='reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
