# Generated by Django 4.2.18 on 2025-03-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tasa de cambio USD/VES del BCV', max_digits=12, verbose_name='tasa')),
                ('source', models.CharField(default='BCV', help_text='Fuente de la tasa de cambio', max_length=100, verbose_name='fuente')),
                ('source_url', models.URLField(blank=True, help_text='URL de la fuente de donde se obtuvo la tasa', null=True, verbose_name='URL fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si es la tasa activa actual', verbose_name='activa')),
                ('obtained_automatically', models.BooleanField(default=True, help_text='Indica si la tasa fue obtenida automáticamente o ingresada manualmente', verbose_name='obtenida automáticamente')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-created_at'],
            },
        ),
    ]
