# Generated by Django 4.2.18 on 2025-01-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='V12345678', max_length=20, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(default='+584141234567', max_length=20, verbose_name='WhatsApp number'),
        ),
    ]
