# Generated by Django 4.2.18 on 2025-01-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending_payment', max_length=20, verbose_name='status'),
        ),
    ]
