# Generated by Django 4.2.18 on 2025-03-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('item_type', models.CharField(choices=[('PADDLE', 'Pala'), ('BALLS', 'Pack de Pelotas')], max_length=20, verbose_name='tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rental_items/', verbose_name='imagen')),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
            ],
            options={
                'verbose_name': 'artículo de alquiler',
                'verbose_name_plural': 'artículos de alquiler',
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.rentalitem', verbose_name='artículo')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'alquiler',
                'verbose_name_plural': 'alquileres',
            },
        ),
    ]
